name: Image build and push
run-name: ${{ github.actor }} is building my R project
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/r-project:${{ env.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/r-project:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/r-project:latest
          cache-to: type=inline
